apiVersion: batch/v1
kind: CronJob
metadata:
  name: hola-mundo-cronjob
  namespace: otsugua04-dev
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hola-mundo-cronjob-container
              image: busybox:latest
              command: ["/bin/sh", "-c"]
              args:
              - |
                sleep 10
                echo "hola mundo"
          restartPolicy: Never
  backoffLimit: 2  # Número de reintentos en caso de fallo